# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: All Integration Tests

on:
  push:
    branches: 
    - master
  pull_request:
    branches:     
    - pr-*

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Integration and Unit Tests
      run: mvn -B verify cobertura:cobertura coveralls:report -Dcoveralls.repo.token=${{ secrets.COVERALLS_TOKEN }} --file pom.xml
  
